// Independent audit census; no code imported from the reproduction package.
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <vector>
#include <array>
#include <cmath>
#include <algorithm>
using U=uint64_t; using T=std::array<U,4>;
U modpow(U a,U n,U p){U b=1;for(;n;n>>=1,a=a*a%p)if(n&1)b=b*a%p;return b;}
std::vector<uint16_t> sp;
std::vector<U> fac(U n){std::vector<U> f;if(!(n&1)){f.push_back(2);while(!(n&1))n/=2;}while(n>1){U q=sp[n/2];if(!q)q=n;f.push_back(q);do{n/=q;}while(n%q==0);}return f;}
bool art(U a,U p,const std::vector<U>& f){if(a%p==0)return false;for(U q:f)if(modpow(a,(p-1)/q,p)==1)return false;return true;}
double ent(double a,double b){double s=a+b,z=0;if(a)z-=a*log(a/s);if(b)z-=b*log(b/s);return z;}
double ce(const std::vector<T>& v,bool prev){double z=0,N=0;for(auto t:v){for(auto n:t)N+=n;z+=prev?ent(t[0],t[1])+ent(t[2],t[3]):ent(t[0]+t[2],t[1]+t[3]);}return z/N;}
double heldout(const std::vector<T>& tr,const std::vector<T>& te,bool prev){double z=0,N=0;for(size_t i=0;i<tr.size();i++){auto a=tr[i],b=te[i];for(auto n:b)N+=n;for(int r=0;r<(prev?2:1);r++){double n0=prev?a[r*2]:a[0]+a[2],n1=prev?a[r*2+1]:a[1]+a[3];double p=(n1+0.5)/(n0+n1+1.);double b0=prev?b[r*2]:b[0]+b[2],b1=prev?b[r*2+1]:b[1]+b[3];z-=b0*log1p(-p)+b1*log(p);}}return z/N;}
void stats(const char* name,const std::vector<T>& v,const std::vector<T>& lo,const std::vector<T>& hi,int threshold){U N=0,eligibleN=0;int cells=0,df=0;double delta=0,chi=0;for(auto t:v){U n=t[0]+t[1]+t[2]+t[3];N+=n;double a=t[0]+t[1],b=t[2]+t[3],c=t[0]+t[2],d=t[1]+t[3];if(a&&b&&c&&d){df++;if(n>=(U)threshold){cells++;eligibleN+=n;delta+=n*(t[3]/b-t[1]/a);double cross=(double)t[0]*t[3]-(double)t[1]*t[2];chi+=n*cross*cross/(a*b*c*d);}}}printf("%s N=%llu CE=%.12f CEprev=%.12f gain=%.12f df=%d nominal_bias=%.12f selectedcells=%d selectedN=%llu selecteddelta=%.12f chi=%.6f heldoutCE=%.12f heldoutCEprev=%.12f heldoutgain=%.12f\n",name,(unsigned long long)N,ce(v,false),ce(v,true),ce(v,false)-ce(v,true),df,df/(2.*N),cells,(unsigned long long)eligibleN,delta/eligibleN,chi,heldout(lo,hi,false),heldout(lo,hi,true),heldout(lo,hi,false)-heldout(lo,hi,true));}
int main(int argc,char**argv){U L=argc>1?strtoull(argv[1],0,10):10000000;bool cross=argc>2;sp.resize(L/2+1);for(U p=3;p*p<=L;p+=2)if(!sp[p/2])for(U n=p*p;n<=L;n+=2*p)if(!sp[n/2])sp[n/2]=p;
std::vector<T> g(2000),v120(120*120),v840(840*840),v40(40),lo120(v120.size()),hi120(v120.size()),lo840(v840.size()),hi840(v840.size()),lo40(40),hi40(40);T global{};U np=0,na=0,prevp=0,ex=0,exa=0,exboth=0,exbad=0;bool prev=false;int prevw=0;long double sx=0,sy=0,sxx=0,syy=0,sxy=0;int bases[]={2,3,5,6,7,10,11,13,15,17,21,29};std::vector<T> cb(66),om(66*16),sig(66*1024);U cbN=0;
for(U p=5;p<=L;p+=2)if(!sp[p/2]){auto f=fac(p-1);bool a=art(10,p,f);if(cross){bool aa[12];for(int i=0;i<12;i++)aa[i]=art(bases[i],p,f);int v=0;for(U m=p-1;!(m&1);m/=2)v++;int mask=0,big=0;int qs[]={3,5,7,11,13};for(U q:f)if(q>13)big++;for(int i=0;i<5;i++)if((p-1)%qs[i]==0)mask|=1<<i;int code=((std::min(v,4)-1)*32+mask)*4+std::min(big,3);int k=0;for(int i=0;i<12;i++)for(int j=i+1;j<12;j++,k++){int x=2*aa[i]+aa[j];cb[k][x]++;om[k*16+f.size()][x]++;sig[k*1024+code][x]++;}cbN++;}
if(p<7)continue;np++;na+=a;if(prevp){int k=2*prev+a;U gap=p-prevp;global[k]++;if(gap<g.size())g[gap][k]++;v40[gap%40][k]++;(p<L/2?lo40:hi40)[gap%40][k]++;int i=(prevp%120)*120+p%120,j=(prevp%840)*840+p%840;v120[i][k]++;v840[j][k]++;(p<L/2?lo120:hi120)[i][k]++;(p<L/2?lo840:hi840)[j][k]++;if(gap%40==20){ex++;exa+=prev;exboth+=prev&&a;exbad+=(modpow(10,(p-1)/2,p)==1)==(modpow(10,(prevp-1)/2,prevp)==1);}sx+=prevw;sy+=f.size();sxx+=prevw*prevw;syy+=f.size()*f.size();sxy+=prevw*f.size();}prevp=p;prev=a;prevw=f.size();}
printf("limit=%llu primes=%llu Artin=%llu final=%llu table=%llu,%llu,%llu,%llu\n",L,np,na,prevp,global[0],global[1],global[2],global[3]);U N=np-1;double d=double(global[3])/(global[2]+global[3])-double(global[1])/(global[0]+global[1]);double det=(double)global[0]*global[3]-(double)global[1]*global[2];double chi=N*det*det/((double)(global[0]+global[1])*(global[2]+global[3])*(global[0]+global[2])*(global[1]+global[3]));printf("delta=%.12f chi=%.9f omega_r=%.12Lf marginalCE=%.12f exclusion=%llu prevA=%llu both=%llu flip_fail=%llu\n",d,chi,(N*sxy-sx*sy)/sqrtl((N*sxx-sx*sx)*(N*syy-sy*sy)),ent(global[0]+global[2],global[1]+global[3])/N,ex,exa,exboth,exbad);
stats("mod120",v120,lo120,hi120,5000);stats("mod840",v840,lo840,hi840,2000);stats("gap40",v40,lo40,hi40,0);for(int gap:{20,40,60}){auto t=g[gap];printf("gap=%d table=%llu,%llu,%llu,%llu delta=%.12f\n",gap,t[0],t[1],t[2],t[3],double(t[3])/(t[2]+t[3])-double(t[1])/(t[0]+t[1]));}
if(cross){auto phi=[](T t){double a=t[0]+t[1],b=t[2]+t[3],c=t[0]+t[2],d=t[1]+t[3];return a*b*c*d?((double)t[0]*t[3]-(double)t[1]*t[2])/sqrt(a*b*c*d):NAN;};double means[3]={};int pos=0,k=0;for(int i=0;i<12;i++)for(int j=i+1;j<12;j++,k++){double ph=phi(cb[k]);pos+=ph>0;means[0]+=ph;double cond[2]={};for(int z=0;z<2;z++){int width=z?1024:16;auto& tb=z?sig:om;double sum=0,nn=0;for(int c=0;c<width;c++){auto t=tb[k*width+c];U n=t[0]+t[1]+t[2]+t[3];double pp=phi(t);if(n>=200&&std::isfinite(pp)){sum+=n*pp;nn+=n;}}cond[z]=sum/nn;means[z+1]+=cond[z];}printf("cross %d,%d phi=%.9f omega=%.9f sig=%.9f\n",bases[i],bases[j],ph,cond[0],cond[1]);}printf("cross_summary N=%llu pos=%d mean=%.9f omega=%.9f sig=%.9f\n",cbN,pos,means[0]/66,means[1]/66,means[2]/66);}
}
